# Generated by Django 3.2.6 on 2021-10-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='porc_iva',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (0, 0)], default=0),
        ),
    ]
