# Generated by Django 3.2.6 on 2021-10-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_productoservicio_porc_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='porc_iva',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (0, '0')], default=0),
        ),
    ]
