# Generated by Django 3.2.6 on 2021-10-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_alter_productoservicio_porc_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
