# Generated by Django 3.2.6 on 2021-10-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_alter_productoservicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
