# Generated by Django 3.2.6 on 2021-10-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0007_alter_productoservicio_porc_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='existencia',
            field=models.FloatField(default=0),
        ),
    ]
