# Generated by Django 3.2.6 on 2021-10-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto_pago', models.FloatField(default=0)),
                ('concepto_pago', models.CharField(max_length=200)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.factura')),
            ],
        ),
    ]
