# Generated by Django 3.2.6 on 2021-11-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0012_auto_20211104_1146'),
        ('Pagos', '0002_alter_pagos_fecha_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagosRealizados',
            fields=[
                ('id_pago_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pago', models.FloatField(default=0)),
                ('concepto_pago', models.CharField(max_length=200)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.facturacompra')),
            ],
        ),
    ]
