# Generated by Django 3.2.6 on 2021-11-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0003_pagosrealizados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagosrealizados',
            old_name='id_pago_compra',
            new_name='id_pago',
        ),
    ]
