# Generated by Django 3.1.6 on 2021-09-05 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_alter_cliente_cedula_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo_paciente', models.CharField(max_length=100)),
                ('raza_paciente', models.CharField(max_length=100)),
                ('especie_paciente', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.cliente')),
            ],
        ),
    ]
