# Generated by Django 3.2.6 on 2021-10-21 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0003_vacunacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_historial', models.DateField()),
                ('descripcion_historial', models.CharField(max_length=255)),
                ('id_paciente_historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacientes.paciente')),
            ],
        ),
    ]
