# Generated by Django 3.2.6 on 2021-10-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_alter_cliente_cedula_cliente'),
        ('Inventario', '0002_productoservicio_porc_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subTotal', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('monto_exento', models.FloatField(default=0)),
                ('monto_iva', models.FloatField(default=0)),
                ('monto_gravado', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('precio', models.FloatField(default=0)),
                ('subTotalDetalle', models.FloatField(default=0)),
                ('descuentoDetalle', models.FloatField(default=0)),
                ('totalDetalle', models.FloatField(default=0)),
                ('monto_exento_det', models.FloatField(default=0)),
                ('monto_iva_det', models.FloatField(default=0)),
                ('monto_gravado_det', models.FloatField(default=0)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.productoservicio')),
            ],
            options={
                'verbose_name': 'Detalle factura',
                'verbose_name_plural': 'Detalle facturas',
            },
        ),
    ]
