# Generated by Django 3.2.6 on 2021-10-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_factura_estado_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id_timbrado', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_timbrado', models.CharField(max_length=10, verbose_name='Nro. Timbrado:')),
                ('numero_inicio', models.IntegerField(default=0, verbose_name='Nro. Inicio:')),
                ('numero_fin', models.IntegerField(default=0, verbose_name='Nro. Fin')),
                ('numero_actual', models.IntegerField(default=1, verbose_name='Nro. Actual')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento:')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('ruc', models.CharField(default='0', max_length=10, verbose_name='Ruc')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='nro_factura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='ruc',
            field=models.CharField(default='0', max_length=10, verbose_name='Ruc'),
        ),
        migrations.AddField(
            model_name='factura',
            name='timbrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturacion.timbrado'),
        ),
    ]
