# Generated by Django 3.2.6 on 2021-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_auto_20211030_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbrado',
            name='establecimiento',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='timbrado',
            name='punto_de_emision',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='nro_factura',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
