# Generated by Django 3.2.6 on 2021-10-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0004_auto_20211030_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timbrado',
            name='establecimiento',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='timbrado',
            name='punto_de_emision',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
