# Generated by Django 3.2.5 on 2021-08-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(default=0),
        ),
    ]
