# Generated by Django 3.2.2 on 2021-09-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula_cliente',
            field=models.IntegerField(),
        ),
    ]
