# Generated by Django 3.2.6 on 2021-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_auto_20211027_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='numero_factura',
            field=models.CharField(max_length=50),
        ),
    ]
