# Generated by Django 3.2.6 on 2021-11-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_alter_productoservicio_existencia'),
        ('Proveedores', '0001_initial'),
        ('Compras', '0003_alter_facturacompra_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_factura',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='numero_factura',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subTotal', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('monto_exento', models.FloatField(default=0)),
                ('monto_iva', models.FloatField(default=0)),
                ('monto_gravado', models.FloatField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'OrdenCompra',
                'verbose_name_plural': 'OrdenesCompras',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('precio', models.FloatField(default=0)),
                ('subTotalDetalle', models.FloatField(default=0)),
                ('descuentoDetalle', models.FloatField(default=0)),
                ('totalDetalle', models.FloatField(default=0)),
                ('monto_exento_det', models.FloatField(default=0)),
                ('monto_iva_det', models.FloatField(default=0)),
                ('monto_gravado_det', models.FloatField(default=0)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compras.ordencompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.productoservicio')),
            ],
            options={
                'verbose_name': 'Detalle orden',
                'verbose_name_plural': 'Detalle ordenes',
            },
        ),
    ]
