# Generated by Django 3.2.6 on 2021-11-03 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0004_auto_20211102_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='id_ref_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Compras.ordencompra'),
        ),
    ]
