# Generated by Django 3.2.6 on 2021-11-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0006_alter_facturacompra_id_ref_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='id_ref_compra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='numero_factura',
            field=models.CharField(default='sin fecha', max_length=50),
        ),
    ]
