# Generated by Django 3.2.6 on 2021-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0007_auto_20211104_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='id_ref_compra',
            field=models.IntegerField(null=True),
        ),
    ]
