# Generated by Django 3.2.6 on 2021-11-04 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0008_alter_facturacompra_id_ref_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_factura',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='id_ref_compra',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='numero_factura',
            field=models.CharField(default='sin factura', max_length=50),
        ),
    ]
