# Generated by Django 3.2.6 on 2021-11-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0009_auto_20211104_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='numero_factura',
            field=models.CharField(default='sin factura', max_length=50, null=True),
        ),
    ]
