# Generated by Django 3.2.6 on 2021-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0011_auto_20211104_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='estado_factura',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='estado_orden',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Facturado', 'Facturado')], default='Pendiente', max_length=20),
        ),
    ]
